### ISSUE TITLE
Use versioning for the docker image

### ISSUE THREAD

**Issue by emirotin** [resin-os/resin-yocto-scripts#32]
The plan is simple: keep a version file for the docker image
It has to be bumped when the breaking changes are added to the dockerfile
It has to be read when building the docker image, and used to tag that image
It has to be read when _using_ the docker image (to load the image with the corresponding tag).

As the file is available inside of this repo (that is used as a submodule) it should provide the seamless integration with the current process (as the submodule is updated the file will be updated, etc.)

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#87
